"""initial schema: events + calibrations

Revision ID: ce995726050e
Revises: 
Create Date: 2026-05-28 15:15:34.750125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce995726050e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.Column('mm_per_px_l2r', sa.Numeric(), nullable=False),
    sa.Column('mm_per_px_r2l', sa.Numeric(), nullable=False),
    sa.Column('reference_distance_mm', sa.Numeric(), nullable=False),
    sa.Column('reference_points_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calibrations', schema=None) as batch_op:
        batch_op.create_index('one_active_calibration', ['active'], unique=True, sqlite_where=sa.text('active = 1'))

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts_utc', sa.DateTime(), nullable=False),
    sa.Column('speed_kph', sa.Numeric(), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('frame_count', sa.Integer(), nullable=False),
    sa.Column('track_len_px', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('thumb_path', sa.Text(), nullable=False),
    sa.Column('calibration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calibration_id'], ['calibrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('events_ts', ['ts_utc'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('events_ts')

    op.drop_table('events')
    with op.batch_alter_table('calibrations', schema=None) as batch_op:
        batch_op.drop_index('one_active_calibration', sqlite_where=sa.text('active = 1'))

    op.drop_table('calibrations')
    # ### end Alembic commands ###
